### ISSUE TITLE
Its not working anymore :(

### ISSUE THREAD

**Issue by shamim4s** [Avdushin/DOBROAI#4]
Hi,
can you check its not working.
![Screenshot 2023-11-03 122020](https://github.com/Avdushin/DOBROAI/assets/85999549/281a4198-da78-4d61-b898-bf0848de51e8)

**Comment by Avdushin** [comment]
Greetings @shamim4s! The error is probably related to the OpenAI API token :(

**Comment by shamim4s** [comment]
Is there any way to solve it ?
I have tried with new generated key from my account. But it's same .

**Comment by Avdushin** [comment]
Re-generating the token will not help (You need to create a new OpenAI account

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ThomasBrickerBK, @IvanRockMen, @resteem, @avsprv, @Evelona, @YarynaD, @HomeSweet, @foxCanFly, @veremey, @narminmolina, @paulradzkov, @Misinin, @micro-chipset, @gabdulbaroff, @NataliGoIt, @Kasper1999, @abatollo, @alexbaumgertner, @pagyew, @stryukovap, @sammoore, @admake, @Denisovspb, @zamaraevrm, @dshster, @DennisLypovetsky, @ryabykhms, @tigefa4u, @pavelvorobev, @dan-ste, @Star-dev325, @NilsonMarenco, @shemerey, @Denisfront, @popoff, @PavloSukhinin, @Ayoubbensassi, @rmuhamedgaliev, @podkovyrovda, @ddgrgrv, @vladislooove, @9kopb, @euaaaio, @lirioblanko, @uandrew, @qois, @MaccKOT, @alexanderpoilov, @Peter-PM, @KennyNobody
